### PR TITLE
bump elixir-ls version

### PR DESCRIPTION
**Pull request by princemaple**

### CODE REVIEW

**Comment by ihabunek** [comment]
@princemaple I'm getting a different checksum, could you double-check?

```
λ wget https://github.com/elixir-lsp/elixir-ls/releases/download/v0.6.0/elixir-ls.zip
λ sha256sum elixir-ls.zip 
2784cf0964ec0723b46ab51edc81f84914b4fd5f6687a00822edd12bb1be6c71  elixir-ls.zip
```

**Comment by princemaple** [comment]
You are right. I got the first one while doing:
```
curl -fSsL https://github.com/elixir-lsp/elixir-ls/releases/download/v0.6.0/elixir-ls.zip
```
and got something `2.67MB`, what's wrong with this?

**Comment by ihabunek** [comment]
Thanks, merged.

**Comment by princemaple** [comment]
Cheers.

**Comment by ihabunek** [comment]
Tagged [0.3.0](https://github.com/sublimelsp/LSP-elixir/releases/tag/0.3.0). Package control should do the rest.

**Comment by ihabunek** [comment]
About `curl`, don't know why that happened. Seems to work ok for me, I get the 1.5Mib archive.

**Comment by princemaple** [comment]
Interesting. Thanks for the confirmation.

**Pull request closed without merging**
